set_property PACKAGE_PIN W7 [get_ports segmentCode[0]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[0]]
set_property PACKAGE_PIN W6 [get_ports segmentCode[1]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[1]]
set_property PACKAGE_PIN U8 [get_ports segmentCode[2]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[2]]
set_property PACKAGE_PIN V8 [get_ports segmentCode[3]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[3]]
set_property PACKAGE_PIN U5 [get_ports segmentCode[4]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[4]]
set_property PACKAGE_PIN V5 [get_ports segmentCode[5]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[5]]
set_property PACKAGE_PIN U7 [get_ports segmentCode[6]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[6]]
set_property PACKAGE_PIN V7 [get_ports segmentCode[7]]
set_property IOSTANDARD LVCMOS33 [get_ports segmentCode[7]]

set_property PACKAGE_PIN U2 [get_ports enable[3]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[3]]
set_property PACKAGE_PIN U4 [get_ports enable[2]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[2]]
set_property PACKAGE_PIN V4 [get_ports enable[1]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[1]]
set_property PACKAGE_PIN W4 [get_ports enable[0]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[0]]

set_property PACKAGE_PIN W19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property PACKAGE_PIN W5 [get_ports basys3Clk]
set_property IOSTANDARD LVCMOS33 [get_ports basys3Clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} {get_ports basys3Clk}